### ISSUE TITLE
Move leap_year.rb to /leap-year/leap_year.rb

### ISSUE THREAD

**Issue by casi** [marksiemers/ruby-to-crystal#3]
Hey @marksiemers, 
first let me thank you for this cool repo! :)

I noticed the `leap_year.rb` is not in the right directory to execute it such as in your example. There will be a `LoadError` when running the respective benchmark.

**Comment by marksiemers** [comment]
That may be one example of a number of problems.

I moved all the examples into the `src` directory from the root, and I didn't double-check everything.

I'll run through and see which examples are broken, and hopefully get a fix out soon.

**Comment by marksiemers** [comment]
@casi - Should be fixed. LMK if any other files have issues.
